name: Auto Approve Dependabot
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: cognitedata/auto-approve-dependabot-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
